-- +micrate Up
ALTER TABLE announcements
ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE
USING created_at AT TIME ZONE 'UTC';

ALTER TABLE announcements
ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE
USING updated_at AT TIME ZONE 'UTC';

ALTER TABLE users
ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE
USING created_at AT TIME ZONE 'UTC';

ALTER TABLE users
ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE
USING updated_at AT TIME ZONE 'UTC';

-- +micrate Down
ALTER TABLE announcements
ALTER COLUMN created_at TYPE TIMESTAMP
USING created_at AT TIME ZONE 'UTC';

ALTER TABLE announcements
ALTER COLUMN updated_at TYPE TIMESTAMP
USING updated_at AT TIME ZONE 'UTC';

ALTER TABLE users
ALTER COLUMN created_at TYPE TIMESTAMP
USING created_at AT TIME ZONE 'UTC';

ALTER TABLE users
ALTER COLUMN updated_at TYPE TIMESTAMP
USING updated_at AT TIME ZONE 'UTC';
